[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.esotericsoftware:kryo:5.5.0"
  api project(':shared')
  implementation 'com.google.code.gson:gson:2.10.1'

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }

  // برای ارتباطات شبکه (کلاینت-سرور)
  implementation 'com.esotericsoftware:kryonet:2.22.0-RC1'

  // برای ساخت و مدیریت توکن‌های JWT (احراز هویت)
  // پیاده‌سازی اصلی
  implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
  // پیاده‌سازی زمان اجرا (Runtime)
  runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
  runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5' // یا jjwt-gson
}
